server:
  shutdown: immediate


management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

# Localstack settings
aws:
  sqs_endpoint_url: "http://localhost:4566"
  access_key_id: foobar
  secret_access_key: foobar
  region_name: eu-west-2
  sqs:
    queue_name: "crime-portal-gateway-queue"

aws_access_key_id: foobar
aws_secret_access_key: foobar
