server:
  shutdown: immediate
  port: 8081

# Localstack settings
hmpps.sqs:
  provider: localstack
  queues:
    crimeportalgatewayqueue:
      queueName: crime-portal-gateway-queue
      dlqName: crime-portal-gateway-dlq
  topics:
    crimeportalgatewaytopic:
      arn: arn:aws:sns:eu-west-2:000000000000:crime-portal-gateway-topic
    courtcaseeventstopic:
      arn: arn:aws:sns:eu-west-2:000000000000:court-case-events-topic
