version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.1
  jira: circleci/jira@1.2.2

jobs:
  validate:
    executor:
      name: hmpps/java
      tag: "16.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew -Dorg.gradle.jvmargs="--illegal-access=permit" -Dkotlin.daemon.jvm.options="--illegal-access=permit" check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - jira/notify:
          token_name: JIRA_CIRCLE_TOKEN
          job_type: build

  deploy_dev:
    executor: deployer
    steps:
      - deploy_to_env:
          env: "dev"
      - jira/notify:
          environment: dev
          environment_type: development
          token_name: JIRA_CIRCLE_TOKEN
          job_type: deployment
  deploy_preprod:
    executor: deployer
    steps:
      - deploy_to_env:
          env: "preprod"
      - jira/notify:
          environment: preprod
          environment_type: testing
          token_name: JIRA_CIRCLE_TOKEN
          job_type: deployment
  deploy_prod:
    executor: deployer
    steps:
      - deploy_to_env:
          env: "prod"
      - jira/notify:
          environment: prod
          environment_type: production
          token_name: JIRA_CIRCLE_TOKEN
          job_type: deployment

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - build_docker
            - helm_lint
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - hmpps-common-vars
            - court-probation-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_channel_name: probation_in_court_dev
          slack_notification: true
          context:
            - hmpps-common-vars
            - court-probation-prod
          requires:
            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          context:
            - hmpps-common-vars

