version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.14.3
  jira: circleci/jira@1.3.1

parameters:
  additional_docker_build_args:
    type: string
    default: ""

jobs:
  build:
    executor:
      name: hmpps/java
      tag: "15.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run: ./gradlew build
      - run:
          name: Record the Application Version
          command: |
            $JAVA_HOME/bin/jar xvf build/libs/court-list-splitter-*.jar META-INF/build-info.properties
            APP_VERSION=$(grep 'build.version=' META-INF/build-info.properties | awk -F= '{print $2}')
            rm META-INF/build-info.properties
            # make up a good version name
            SHORT_HASH=$(git rev-parse --short HEAD)
            TAG=${APP_VERSION}.${SHORT_HASH}
            if [[ "${CIRCLE_BRANCH}" == "main" ]]; then
              TAG=${APP_VERSION}
            fi
            echo $TAG > ./app_version.txt
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle.kts
            - app_version.txt

  test-integration:
    executor:
      name: hmpps/localstack
      services: sqs,sns
      jdk_tag: "15.0"
      localstack_tag: "0.11.2"
    steps:
      - checkout
      - hmpps/install_aws_cli
      - run:
          name: Wait for SQS to be ready
          command: curl -4 --connect-timeout 30 --retry-connrefused --retry 20 --retry-delay 5 http://localhost:4566
      - run:
          name: Set up queues
          command: bash src/test/resources/localstack/setup-sqs.sh
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          environment:
            AWS_PROVIDER: localstack
            SPRING_PROFILES_ACTIVE: test
          command: ./gradlew integrationTest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          additional_docker_build_args: << pipeline.parameters.additional_docker_build_args >>
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          helm_additional_args: --values ./court-list-splitter/values-live.yaml
          context:
            - hmpps-common-vars
            - court-probation-live-dev
          filters:
            branches:
              only:
                - main
          requires:
            - build
            - build_docker
            - helm_lint
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          helm_additional_args: --values ./court-list-splitter/values-live.yaml
          context:
            - hmpps-common-vars
            - court-probation-live-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          helm_additional_args: --values ./court-list-splitter/values-live.yaml
          slack_channel_name: probation_in_court_dev
          slack_notification: true
          context:
            - hmpps-common-vars
            - court-probation-live-prod
          requires:
            - request-prod-approval

  test-integration:
    jobs:
      - test-integration

  security:
    triggers:
      - schedule:
          cron: "36 4 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          slack_channel: probation_in_court_dev
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: probation_in_court_dev
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: probation_in_court_dev
          context:
            - hmpps-common-vars
            - veracode-credentials
  security-weekly:
    triggers:
      - schedule:
          cron: "30 6 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: probation_in_court_dev
          context:
            - veracode-credentials
            - hmpps-common-vars
