generic-service:
  springProfiles: sqs-read

  ingress:
    enabled: true
    enable_whitelist: true
    hosts:
      - host: court-list-splitter-dev.hmpps.service.justice.gov.uk
        cert_secret: court-probation-dev-cert-secret
    path: /

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 100

  resources:
    cpu:
      limit: 5000m
      request: 250m
    memory:
      limit: 1200Mi
      request: 350Mi

