generic-service:
  springProfiles: sqs-read

  ingress:
    host: court-list-splitter-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-preprod-cert-secret

  resources:
    limits:
      cpu: 5000m
      memory: 1200Mi
    requests:
      cpu: 500m
      memory: 700Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 100
