generic-service:
  springProfiles: sqs-read

  ingress:
    enabled: true
    enable_whitelist: true
    hosts:
      - host: court-list-splitter.hmpps.service.justice.gov.uk
        cert_secret: court-probation-cert-secret
    path: /

  resources:
    cpu:
      limit: 5000m
      request: 500m
    memory:
      limit: 1200Mi
      request: 700Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 100
