generic-service:
  springProfiles: sqs-read

  ingress:
    enabled: true
    enable_whitelist: true
    hosts:
      - host: court-list-splitter-dev.hmpps.service.justice.gov.uk
        cert_secret: court-probation-dev-cert-secret
    path: /

