generic-service:
  springProfiles: ""

  ingress:
    enabled: true
    enable_whitelist: true
    hosts:
      - host: court-list-splitter-preprod.hmpps.service.justice.gov.uk
        cert_secret: court-probation-preprod-cert-secret
    path: /

  resources:
    cpu:
      limit: 1000m
      request: 50m
    memory:
      limit: 1000Mi
      request: 500Mi
