generic-service:
  springProfiles: sqs-read

  ingress:
    host: court-list-splitter-dev.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-dev-cert-secret

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 100

  resources:
    limits:
      cpu: 5000m
      memory: 1200Mi
    requests:
      cpu: 250m
      memory: 350Mi

