generic-service:
  nameOverride: court-list-splitter

  replicaCount: 4

  serviceAccountName: "court-case-service"

  image:
    repository: quay.io/hmpps/court-list-splitter
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    v1_2_enabled: true
    v0_47_enabled: false
    enabled: true
    enable_whitelist: true
    path: /

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash,sqs-read"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    court-list-splitter:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    crime-portal-gateway-queue-credentials:
      AWS_SQS_QUEUE_NAME: sqs_name
      AWS_SQS_ENDPOINT_URL: sqs_id
    court-case-events-topic:
      AWS_SNS_TOPIC_ARN: topic_arn

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: court-list-splitter
  alertSeverity: prepare-a-case
