---
generic-service:
  nameOverride: court-list-splitter

  replicaCount: 4

  image:
    repository: quay.io/hmpps/court-list-splitter
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    v1_2_enabled: true
    v0_47_enabled: false
    enabled: true
    enable_whitelist: true
    path: /

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash,sqs-read"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    court-list-splitter:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    crime-portal-gateway-queue-credentials:
      AWS_ACCESS_KEY_ID: access_key_id
      AWS_SECRET_ACCESS_KEY: secret_access_key
      AWS_SQS_QUEUE_NAME: sqs_name
      AWS_SQS_ENDPOINT_URL: sqs_id
    court-case-events-topic:
      AWS_SNS_ACCESS_KEY_ID: access_key_id
      AWS_SNS_SECRET_ACCESS_KEY: secret_access_key
      AWS_SNS_TOPIC_ARN: topic_arn

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: court-list-splitter
  alertSeverity: prepare-a-case
